// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.20459
//    <NameSpace>XlsxLib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLasyLoading>True</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XlsxLib
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Workbook
    {

        private CT_FileVersion fileVersionField;

        private CT_FileSharing fileSharingField;

        private CT_WorkbookPr workbookPrField;

        private CT_WorkbookProtection workbookProtectionField;

        private List<CT_BookView> bookViewsField;

        private List<CT_Sheet> sheetsField;

        private CT_FunctionGroups functionGroupsField;

        private List<CT_ExternalReference> externalReferencesField;

        private List<CT_DefinedName> definedNamesField;

        private CT_CalcPr calcPrField;

        private CT_OleSize oleSizeField;

        private List<CT_CustomWorkbookView> customWorkbookViewsField;

        private List<CT_PivotCache> pivotCachesField;

        private CT_SmartTagPr smartTagPrField;

        private List<CT_SmartTagType> smartTagTypesField;

        private CT_WebPublishing webPublishingField;

        private List<CT_FileRecoveryPr> fileRecoveryPrField;

        private CT_WebPublishObjects webPublishObjectsField;

        private CT_ExtensionList extLstField;

        public CT_FileVersion fileVersion
        {
            get
            {
                if ((this.fileVersionField == null))
                {
                    this.fileVersionField = new CT_FileVersion();
                }
                return this.fileVersionField;
            }
            set
            {
                this.fileVersionField = value;
            }
        }

        public CT_FileSharing fileSharing
        {
            get
            {
                if ((this.fileSharingField == null))
                {
                    this.fileSharingField = new CT_FileSharing();
                }
                return this.fileSharingField;
            }
            set
            {
                this.fileSharingField = value;
            }
        }

        public CT_WorkbookPr workbookPr
        {
            get
            {
                if ((this.workbookPrField == null))
                {
                    this.workbookPrField = new CT_WorkbookPr();
                }
                return this.workbookPrField;
            }
            set
            {
                this.workbookPrField = value;
            }
        }

        public CT_WorkbookProtection workbookProtection
        {
            get
            {
                if ((this.workbookProtectionField == null))
                {
                    this.workbookProtectionField = new CT_WorkbookProtection();
                }
                return this.workbookProtectionField;
            }
            set
            {
                this.workbookProtectionField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("workbookView", IsNullable = false)]
        public List<CT_BookView> bookViews
        {
            get
            {
                if ((this.bookViewsField == null))
                {
                    this.bookViewsField = new List<CT_BookView>();
                }
                return this.bookViewsField;
            }
            set
            {
                this.bookViewsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("sheet", IsNullable = false)]
        public List<CT_Sheet> sheets
        {
            get
            {
                if ((this.sheetsField == null))
                {
                    this.sheetsField = new List<CT_Sheet>();
                }
                return this.sheetsField;
            }
            set
            {
                this.sheetsField = value;
            }
        }

        public CT_FunctionGroups functionGroups
        {
            get
            {
                if ((this.functionGroupsField == null))
                {
                    this.functionGroupsField = new CT_FunctionGroups();
                }
                return this.functionGroupsField;
            }
            set
            {
                this.functionGroupsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("externalReference", IsNullable = false)]
        public List<CT_ExternalReference> externalReferences
        {
            get
            {
                if ((this.externalReferencesField == null))
                {
                    this.externalReferencesField = new List<CT_ExternalReference>();
                }
                return this.externalReferencesField;
            }
            set
            {
                this.externalReferencesField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("definedName", IsNullable = false)]
        public List<CT_DefinedName> definedNames
        {
            get
            {
                if ((this.definedNamesField == null))
                {
                    this.definedNamesField = new List<CT_DefinedName>();
                }
                return this.definedNamesField;
            }
            set
            {
                this.definedNamesField = value;
            }
        }

        public CT_CalcPr calcPr
        {
            get
            {
                if ((this.calcPrField == null))
                {
                    this.calcPrField = new CT_CalcPr();
                }
                return this.calcPrField;
            }
            set
            {
                this.calcPrField = value;
            }
        }

        public CT_OleSize oleSize
        {
            get
            {
                if ((this.oleSizeField == null))
                {
                    this.oleSizeField = new CT_OleSize();
                }
                return this.oleSizeField;
            }
            set
            {
                this.oleSizeField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("customWorkbookView", IsNullable = false)]
        public List<CT_CustomWorkbookView> customWorkbookViews
        {
            get
            {
                if ((this.customWorkbookViewsField == null))
                {
                    this.customWorkbookViewsField = new List<CT_CustomWorkbookView>();
                }
                return this.customWorkbookViewsField;
            }
            set
            {
                this.customWorkbookViewsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("pivotCache", IsNullable = false)]
        public List<CT_PivotCache> pivotCaches
        {
            get
            {
                if ((this.pivotCachesField == null))
                {
                    this.pivotCachesField = new List<CT_PivotCache>();
                }
                return this.pivotCachesField;
            }
            set
            {
                this.pivotCachesField = value;
            }
        }

        public CT_SmartTagPr smartTagPr
        {
            get
            {
                if ((this.smartTagPrField == null))
                {
                    this.smartTagPrField = new CT_SmartTagPr();
                }
                return this.smartTagPrField;
            }
            set
            {
                this.smartTagPrField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("smartTagType", IsNullable = false)]
        public List<CT_SmartTagType> smartTagTypes
        {
            get
            {
                if ((this.smartTagTypesField == null))
                {
                    this.smartTagTypesField = new List<CT_SmartTagType>();
                }
                return this.smartTagTypesField;
            }
            set
            {
                this.smartTagTypesField = value;
            }
        }

        public CT_WebPublishing webPublishing
        {
            get
            {
                if ((this.webPublishingField == null))
                {
                    this.webPublishingField = new CT_WebPublishing();
                }
                return this.webPublishingField;
            }
            set
            {
                this.webPublishingField = value;
            }
        }

        public List<CT_FileRecoveryPr> fileRecoveryPr
        {
            get
            {
                if ((this.fileRecoveryPrField == null))
                {
                    this.fileRecoveryPrField = new List<CT_FileRecoveryPr>();
                }
                return this.fileRecoveryPrField;
            }
            set
            {
                this.fileRecoveryPrField = value;
            }
        }

        public CT_WebPublishObjects webPublishObjects
        {
            get
            {
                if ((this.webPublishObjectsField == null))
                {
                    this.webPublishObjectsField = new CT_WebPublishObjects();
                }
                return this.webPublishObjectsField;
            }
            set
            {
                this.webPublishObjectsField = value;
            }
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FileVersion
    {

        private string appNameField;

        private string lastEditedField;

        private string lowestEditedField;

        private string rupBuildField;

        private string codeNameField;

        public string appName
        {
            get
            {
                return this.appNameField;
            }
            set
            {
                this.appNameField = value;
            }
        }

        public string lastEdited
        {
            get
            {
                return this.lastEditedField;
            }
            set
            {
                this.lastEditedField = value;
            }
        }

        public string lowestEdited
        {
            get
            {
                return this.lowestEditedField;
            }
            set
            {
                this.lowestEditedField = value;
            }
        }

        public string rupBuild
        {
            get
            {
                return this.rupBuildField;
            }
            set
            {
                this.rupBuildField = value;
            }
        }

        public string codeName
        {
            get
            {
                return this.codeNameField;
            }
            set
            {
                this.codeNameField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_WebPublishObject
    {

        private uint idField;

        private string divIdField;

        private string sourceObjectField;

        private string destinationFileField;

        private string titleField;

        private bool autoRepublishField;

        public CT_WebPublishObject()
        {
            this.autoRepublishField = false;
        }

        public uint id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        public string divId
        {
            get
            {
                return this.divIdField;
            }
            set
            {
                this.divIdField = value;
            }
        }

        public string sourceObject
        {
            get
            {
                return this.sourceObjectField;
            }
            set
            {
                this.sourceObjectField = value;
            }
        }

        public string destinationFile
        {
            get
            {
                return this.destinationFileField;
            }
            set
            {
                this.destinationFileField = value;
            }
        }

        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool autoRepublish
        {
            get
            {
                return this.autoRepublishField;
            }
            set
            {
                this.autoRepublishField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_WebPublishObjects
    {

        private List<CT_WebPublishObject> webPublishObjectField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_WebPublishObject> webPublishObject
        {
            get
            {
                if ((this.webPublishObjectField == null))
                {
                    this.webPublishObjectField = new List<CT_WebPublishObject>();
                }
                return this.webPublishObjectField;
            }
            set
            {
                this.webPublishObjectField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FileRecoveryPr
    {

        private bool autoRecoverField;

        private bool crashSaveField;

        private bool dataExtractLoadField;

        private bool repairLoadField;

        public CT_FileRecoveryPr()
        {
            this.autoRecoverField = true;
            this.crashSaveField = false;
            this.dataExtractLoadField = false;
            this.repairLoadField = false;
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool autoRecover
        {
            get
            {
                return this.autoRecoverField;
            }
            set
            {
                this.autoRecoverField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool crashSave
        {
            get
            {
                return this.crashSaveField;
            }
            set
            {
                this.crashSaveField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool dataExtractLoad
        {
            get
            {
                return this.dataExtractLoadField;
            }
            set
            {
                this.dataExtractLoadField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool repairLoad
        {
            get
            {
                return this.repairLoadField;
            }
            set
            {
                this.repairLoadField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_WebPublishing
    {

        private bool cssField;

        private bool thicketField;

        private bool longFileNamesField;

        private bool vmlField;

        private bool allowPngField;

        private ST_TargetScreenSize targetScreenSizeField;

        private uint dpiField;

        private uint codePageField;

        private bool codePageFieldSpecified;

        public CT_WebPublishing()
        {
            this.cssField = true;
            this.thicketField = true;
            this.longFileNamesField = true;
            this.vmlField = false;
            this.allowPngField = false;
            this.targetScreenSizeField = ST_TargetScreenSize.Item800x600;
            this.dpiField = ((uint)(96));
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool css
        {
            get
            {
                return this.cssField;
            }
            set
            {
                this.cssField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool thicket
        {
            get
            {
                return this.thicketField;
            }
            set
            {
                this.thicketField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool longFileNames
        {
            get
            {
                return this.longFileNamesField;
            }
            set
            {
                this.longFileNamesField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool vml
        {
            get
            {
                return this.vmlField;
            }
            set
            {
                this.vmlField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool allowPng
        {
            get
            {
                return this.allowPngField;
            }
            set
            {
                this.allowPngField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_TargetScreenSize.Item800x600)]
        public ST_TargetScreenSize targetScreenSize
        {
            get
            {
                return this.targetScreenSizeField;
            }
            set
            {
                this.targetScreenSizeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "96")]
        public uint dpi
        {
            get
            {
                return this.dpiField;
            }
            set
            {
                this.dpiField = value;
            }
        }

        public uint codePage
        {
            get
            {
                return this.codePageField;
            }
            set
            {
                this.codePageField = value;
            }
        }

        public bool codePageSpecified
        {
            get
            {
                return this.codePageFieldSpecified;
            }
            set
            {
                this.codePageFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_TargetScreenSize
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("544x376")]
        Item544x376,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("640x480")]
        Item640x480,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("720x512")]
        Item720x512,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("800x600")]
        Item800x600,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1024x768")]
        Item1024x768,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1152x882")]
        Item1152x882,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1152x900")]
        Item1152x900,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1280x1024")]
        Item1280x1024,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1600x1200")]
        Item1600x1200,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1800x1440")]
        Item1800x1440,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1920x1200")]
        Item1920x1200,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_SmartTagType
    {

        private string namespaceUriField;

        private string nameField;

        private string urlField;

        public string namespaceUri
        {
            get
            {
                return this.namespaceUriField;
            }
            set
            {
                this.namespaceUriField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_SmartTagPr
    {

        private bool embedField;

        private ST_SmartTagShow showField;

        public CT_SmartTagPr()
        {
            this.embedField = false;
            this.showField = ST_SmartTagShow.all;
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool embed
        {
            get
            {
                return this.embedField;
            }
            set
            {
                this.embedField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_SmartTagShow.all)]
        public ST_SmartTagShow show
        {
            get
            {
                return this.showField;
            }
            set
            {
                this.showField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_SmartTagShow
    {

        /// <remarks/>
        all,

        /// <remarks/>
        none,

        /// <remarks/>
        noIndicator,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_PivotCache
    {

        private uint cacheIdField;

        private string idField;

        public uint cacheId
        {
            get
            {
                return this.cacheIdField;
            }
            set
            {
                this.cacheIdField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CustomWorkbookView
    {

        private CT_ExtensionList extLstField;

        private string nameField;

        private string guidField;

        private bool autoUpdateField;

        private uint mergeIntervalField;

        private bool mergeIntervalFieldSpecified;

        private bool changesSavedWinField;

        private bool onlySyncField;

        private bool personalViewField;

        private bool includePrintSettingsField;

        private bool includeHiddenRowColField;

        private bool maximizedField;

        private bool minimizedField;

        private bool showHorizontalScrollField;

        private bool showVerticalScrollField;

        private bool showSheetTabsField;

        private int xWindowField;

        private int yWindowField;

        private uint windowWidthField;

        private uint windowHeightField;

        private uint tabRatioField;

        private uint activeSheetIdField;

        private bool showFormulaBarField;

        private bool showStatusbarField;

        private ST_Comments showCommentsField;

        private ST_Objects showObjectsField;

        public CT_CustomWorkbookView()
        {
            this.autoUpdateField = false;
            this.changesSavedWinField = false;
            this.onlySyncField = false;
            this.personalViewField = false;
            this.includePrintSettingsField = true;
            this.includeHiddenRowColField = true;
            this.maximizedField = false;
            this.minimizedField = false;
            this.showHorizontalScrollField = true;
            this.showVerticalScrollField = true;
            this.showSheetTabsField = true;
            this.xWindowField = 0;
            this.yWindowField = 0;
            this.tabRatioField = ((uint)(600));
            this.showFormulaBarField = true;
            this.showStatusbarField = true;
            this.showCommentsField = ST_Comments.commIndicator;
            this.showObjectsField = ST_Objects.all;
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool autoUpdate
        {
            get
            {
                return this.autoUpdateField;
            }
            set
            {
                this.autoUpdateField = value;
            }
        }

        public uint mergeInterval
        {
            get
            {
                return this.mergeIntervalField;
            }
            set
            {
                this.mergeIntervalField = value;
            }
        }

        public bool mergeIntervalSpecified
        {
            get
            {
                return this.mergeIntervalFieldSpecified;
            }
            set
            {
                this.mergeIntervalFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool changesSavedWin
        {
            get
            {
                return this.changesSavedWinField;
            }
            set
            {
                this.changesSavedWinField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool onlySync
        {
            get
            {
                return this.onlySyncField;
            }
            set
            {
                this.onlySyncField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool personalView
        {
            get
            {
                return this.personalViewField;
            }
            set
            {
                this.personalViewField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool includePrintSettings
        {
            get
            {
                return this.includePrintSettingsField;
            }
            set
            {
                this.includePrintSettingsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool includeHiddenRowCol
        {
            get
            {
                return this.includeHiddenRowColField;
            }
            set
            {
                this.includeHiddenRowColField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool maximized
        {
            get
            {
                return this.maximizedField;
            }
            set
            {
                this.maximizedField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool minimized
        {
            get
            {
                return this.minimizedField;
            }
            set
            {
                this.minimizedField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showHorizontalScroll
        {
            get
            {
                return this.showHorizontalScrollField;
            }
            set
            {
                this.showHorizontalScrollField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showVerticalScroll
        {
            get
            {
                return this.showVerticalScrollField;
            }
            set
            {
                this.showVerticalScrollField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showSheetTabs
        {
            get
            {
                return this.showSheetTabsField;
            }
            set
            {
                this.showSheetTabsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0)]
        public int xWindow
        {
            get
            {
                return this.xWindowField;
            }
            set
            {
                this.xWindowField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0)]
        public int yWindow
        {
            get
            {
                return this.yWindowField;
            }
            set
            {
                this.yWindowField = value;
            }
        }

        public uint windowWidth
        {
            get
            {
                return this.windowWidthField;
            }
            set
            {
                this.windowWidthField = value;
            }
        }

        public uint windowHeight
        {
            get
            {
                return this.windowHeightField;
            }
            set
            {
                this.windowHeightField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "600")]
        public uint tabRatio
        {
            get
            {
                return this.tabRatioField;
            }
            set
            {
                this.tabRatioField = value;
            }
        }

        public uint activeSheetId
        {
            get
            {
                return this.activeSheetIdField;
            }
            set
            {
                this.activeSheetIdField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showFormulaBar
        {
            get
            {
                return this.showFormulaBarField;
            }
            set
            {
                this.showFormulaBarField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showStatusbar
        {
            get
            {
                return this.showStatusbarField;
            }
            set
            {
                this.showStatusbarField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_Comments.commIndicator)]
        public ST_Comments showComments
        {
            get
            {
                return this.showCommentsField;
            }
            set
            {
                this.showCommentsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_Objects.all)]
        public ST_Objects showObjects
        {
            get
            {
                return this.showObjectsField;
            }
            set
            {
                this.showObjectsField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_Comments
    {

        /// <remarks/>
        commNone,

        /// <remarks/>
        commIndicator,

        /// <remarks/>
        commIndAndComment,
    }

    [System.SerializableAttribute()]
    public enum ST_Objects
    {

        /// <remarks/>
        all,

        /// <remarks/>
        placeholders,

        /// <remarks/>
        none,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_OleSize
    {

        private string refField;

        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CalcPr
    {

        private uint calcIdField;

        private bool calcIdFieldSpecified;

        private ST_CalcMode calcModeField;

        private bool fullCalcOnLoadField;

        private ST_RefMode refModeField;

        private bool iterateField;

        private uint iterateCountField;

        private double iterateDeltaField;

        private bool fullPrecisionField;

        private bool calcCompletedField;

        private bool calcOnSaveField;

        private bool concurrentCalcField;

        private uint concurrentManualCountField;

        private bool concurrentManualCountFieldSpecified;

        private bool forceFullCalcField;

        private bool forceFullCalcFieldSpecified;

        public CT_CalcPr()
        {
            this.calcModeField = ST_CalcMode.auto;
            this.fullCalcOnLoadField = false;
            this.refModeField = ST_RefMode.A1;
            this.iterateField = false;
            this.iterateCountField = ((uint)(100));
            this.iterateDeltaField = 0.001D;
            this.fullPrecisionField = true;
            this.calcCompletedField = true;
            this.calcOnSaveField = true;
            this.concurrentCalcField = true;
        }

        public uint calcId
        {
            get
            {
                return this.calcIdField;
            }
            set
            {
                this.calcIdField = value;
            }
        }

        public bool calcIdSpecified
        {
            get
            {
                return this.calcIdFieldSpecified;
            }
            set
            {
                this.calcIdFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_CalcMode.auto)]
        public ST_CalcMode calcMode
        {
            get
            {
                return this.calcModeField;
            }
            set
            {
                this.calcModeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool fullCalcOnLoad
        {
            get
            {
                return this.fullCalcOnLoadField;
            }
            set
            {
                this.fullCalcOnLoadField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_RefMode.A1)]
        public ST_RefMode refMode
        {
            get
            {
                return this.refModeField;
            }
            set
            {
                this.refModeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool iterate
        {
            get
            {
                return this.iterateField;
            }
            set
            {
                this.iterateField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "100")]
        public uint iterateCount
        {
            get
            {
                return this.iterateCountField;
            }
            set
            {
                this.iterateCountField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0.001D)]
        public double iterateDelta
        {
            get
            {
                return this.iterateDeltaField;
            }
            set
            {
                this.iterateDeltaField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool fullPrecision
        {
            get
            {
                return this.fullPrecisionField;
            }
            set
            {
                this.fullPrecisionField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool calcCompleted
        {
            get
            {
                return this.calcCompletedField;
            }
            set
            {
                this.calcCompletedField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool calcOnSave
        {
            get
            {
                return this.calcOnSaveField;
            }
            set
            {
                this.calcOnSaveField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool concurrentCalc
        {
            get
            {
                return this.concurrentCalcField;
            }
            set
            {
                this.concurrentCalcField = value;
            }
        }

        public uint concurrentManualCount
        {
            get
            {
                return this.concurrentManualCountField;
            }
            set
            {
                this.concurrentManualCountField = value;
            }
        }

        public bool concurrentManualCountSpecified
        {
            get
            {
                return this.concurrentManualCountFieldSpecified;
            }
            set
            {
                this.concurrentManualCountFieldSpecified = value;
            }
        }

        public bool forceFullCalc
        {
            get
            {
                return this.forceFullCalcField;
            }
            set
            {
                this.forceFullCalcField = value;
            }
        }

        public bool forceFullCalcSpecified
        {
            get
            {
                return this.forceFullCalcFieldSpecified;
            }
            set
            {
                this.forceFullCalcFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_CalcMode
    {

        /// <remarks/>
        manual,

        /// <remarks/>
        auto,

        /// <remarks/>
        autoNoTable,
    }

    [System.SerializableAttribute()]
    public enum ST_RefMode
    {

        /// <remarks/>
        A1,

        /// <remarks/>
        R1C1,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_DefinedName
    {

        private string nameField;

        private string commentField;

        private string customMenuField;

        private string descriptionField;

        private string helpField;

        private string statusBarField;

        private uint localSheetIdField;

        private bool localSheetIdFieldSpecified;

        private bool hiddenField;

        private bool functionField;

        private bool vbProcedureField;

        private bool xlmField;

        private uint functionGroupIdField;

        private bool functionGroupIdFieldSpecified;

        private string shortcutKeyField;

        private bool publishToServerField;

        private bool workbookParameterField;

        private string valueField;

        public CT_DefinedName()
        {
            this.hiddenField = false;
            this.functionField = false;
            this.vbProcedureField = false;
            this.xlmField = false;
            this.publishToServerField = false;
            this.workbookParameterField = false;
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        public string customMenu
        {
            get
            {
                return this.customMenuField;
            }
            set
            {
                this.customMenuField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string help
        {
            get
            {
                return this.helpField;
            }
            set
            {
                this.helpField = value;
            }
        }

        public string statusBar
        {
            get
            {
                return this.statusBarField;
            }
            set
            {
                this.statusBarField = value;
            }
        }

        public uint localSheetId
        {
            get
            {
                return this.localSheetIdField;
            }
            set
            {
                this.localSheetIdField = value;
            }
        }

        public bool localSheetIdSpecified
        {
            get
            {
                return this.localSheetIdFieldSpecified;
            }
            set
            {
                this.localSheetIdFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool function
        {
            get
            {
                return this.functionField;
            }
            set
            {
                this.functionField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool vbProcedure
        {
            get
            {
                return this.vbProcedureField;
            }
            set
            {
                this.vbProcedureField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool xlm
        {
            get
            {
                return this.xlmField;
            }
            set
            {
                this.xlmField = value;
            }
        }

        public uint functionGroupId
        {
            get
            {
                return this.functionGroupIdField;
            }
            set
            {
                this.functionGroupIdField = value;
            }
        }

        public bool functionGroupIdSpecified
        {
            get
            {
                return this.functionGroupIdFieldSpecified;
            }
            set
            {
                this.functionGroupIdFieldSpecified = value;
            }
        }

        public string shortcutKey
        {
            get
            {
                return this.shortcutKeyField;
            }
            set
            {
                this.shortcutKeyField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool publishToServer
        {
            get
            {
                return this.publishToServerField;
            }
            set
            {
                this.publishToServerField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool workbookParameter
        {
            get
            {
                return this.workbookParameterField;
            }
            set
            {
                this.workbookParameterField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_ExternalReference
    {

        private string idField;

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FunctionGroup
    {

        private string nameField;

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FunctionGroups
    {

        private List<CT_FunctionGroup> functionGroupField;

        private uint builtInGroupCountField;

        public CT_FunctionGroups()
        {
            this.builtInGroupCountField = ((uint)(16));
        }

        public List<CT_FunctionGroup> functionGroup
        {
            get
            {
                if ((this.functionGroupField == null))
                {
                    this.functionGroupField = new List<CT_FunctionGroup>();
                }
                return this.functionGroupField;
            }
            set
            {
                this.functionGroupField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "16")]
        public uint builtInGroupCount
        {
            get
            {
                return this.builtInGroupCountField;
            }
            set
            {
                this.builtInGroupCountField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Sheet
    {

        private string nameField;

        private uint sheetIdField;

        private ST_SheetState stateField;

        private string idField;

        public CT_Sheet()
        {
            this.stateField = ST_SheetState.visible;
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public uint sheetId
        {
            get
            {
                return this.sheetIdField;
            }
            set
            {
                this.sheetIdField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_SheetState.visible)]
        public ST_SheetState state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_SheetState
    {

        /// <remarks/>
        visible,

        /// <remarks/>
        hidden,

        /// <remarks/>
        veryHidden,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_BookView
    {

        private CT_ExtensionList extLstField;

        private ST_Visibility visibilityField;

        private bool minimizedField;

        private bool showHorizontalScrollField;

        private bool showVerticalScrollField;

        private bool showSheetTabsField;

        private int xWindowField;

        private bool xWindowFieldSpecified;

        private int yWindowField;

        private bool yWindowFieldSpecified;

        private uint windowWidthField;

        private bool windowWidthFieldSpecified;

        private uint windowHeightField;

        private bool windowHeightFieldSpecified;

        private uint tabRatioField;

        private uint firstSheetField;

        private uint activeTabField;

        private bool autoFilterDateGroupingField;

        public CT_BookView()
        {
            this.visibilityField = ST_Visibility.visible;
            this.minimizedField = false;
            this.showHorizontalScrollField = true;
            this.showVerticalScrollField = true;
            this.showSheetTabsField = true;
            this.tabRatioField = ((uint)(600));
            this.firstSheetField = ((uint)(0));
            this.activeTabField = ((uint)(0));
            this.autoFilterDateGroupingField = true;
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_Visibility.visible)]
        public ST_Visibility visibility
        {
            get
            {
                return this.visibilityField;
            }
            set
            {
                this.visibilityField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool minimized
        {
            get
            {
                return this.minimizedField;
            }
            set
            {
                this.minimizedField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showHorizontalScroll
        {
            get
            {
                return this.showHorizontalScrollField;
            }
            set
            {
                this.showHorizontalScrollField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showVerticalScroll
        {
            get
            {
                return this.showVerticalScrollField;
            }
            set
            {
                this.showVerticalScrollField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showSheetTabs
        {
            get
            {
                return this.showSheetTabsField;
            }
            set
            {
                this.showSheetTabsField = value;
            }
        }

        public int xWindow
        {
            get
            {
                return this.xWindowField;
            }
            set
            {
                this.xWindowField = value;
            }
        }

        public bool xWindowSpecified
        {
            get
            {
                return this.xWindowFieldSpecified;
            }
            set
            {
                this.xWindowFieldSpecified = value;
            }
        }

        public int yWindow
        {
            get
            {
                return this.yWindowField;
            }
            set
            {
                this.yWindowField = value;
            }
        }

        public bool yWindowSpecified
        {
            get
            {
                return this.yWindowFieldSpecified;
            }
            set
            {
                this.yWindowFieldSpecified = value;
            }
        }

        public uint windowWidth
        {
            get
            {
                return this.windowWidthField;
            }
            set
            {
                this.windowWidthField = value;
            }
        }

        public bool windowWidthSpecified
        {
            get
            {
                return this.windowWidthFieldSpecified;
            }
            set
            {
                this.windowWidthFieldSpecified = value;
            }
        }

        public uint windowHeight
        {
            get
            {
                return this.windowHeightField;
            }
            set
            {
                this.windowHeightField = value;
            }
        }

        public bool windowHeightSpecified
        {
            get
            {
                return this.windowHeightFieldSpecified;
            }
            set
            {
                this.windowHeightFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "600")]
        public uint tabRatio
        {
            get
            {
                return this.tabRatioField;
            }
            set
            {
                this.tabRatioField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint firstSheet
        {
            get
            {
                return this.firstSheetField;
            }
            set
            {
                this.firstSheetField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint activeTab
        {
            get
            {
                return this.activeTabField;
            }
            set
            {
                this.activeTabField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool autoFilterDateGrouping
        {
            get
            {
                return this.autoFilterDateGroupingField;
            }
            set
            {
                this.autoFilterDateGroupingField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_Visibility
    {

        /// <remarks/>
        visible,

        /// <remarks/>
        hidden,

        /// <remarks/>
        veryHidden,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_WorkbookProtection
    {

        private byte[] workbookPasswordField;

        private byte[] revisionsPasswordField;

        private bool lockStructureField;

        private bool lockWindowsField;

        private bool lockRevisionField;

        public CT_WorkbookProtection()
        {
            this.lockStructureField = false;
            this.lockWindowsField = false;
            this.lockRevisionField = false;
        }

        public byte[] workbookPassword
        {
            get {               
                return this.workbookPasswordField;
            }
            set
            {
                this.workbookPasswordField = value;
            }
        }

        public byte[] revisionsPassword
        {
            get {                
                return this.revisionsPasswordField;
            }
            set
            {
                this.revisionsPasswordField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool lockStructure
        {
            get
            {
                return this.lockStructureField;
            }
            set
            {
                this.lockStructureField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool lockWindows
        {
            get
            {
                return this.lockWindowsField;
            }
            set
            {
                this.lockWindowsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool lockRevision
        {
            get
            {
                return this.lockRevisionField;
            }
            set
            {
                this.lockRevisionField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_WorkbookPr
    {

        private bool date1904Field;

        private ST_Objects showObjectsField;

        private bool showBorderUnselectedTablesField;

        private bool filterPrivacyField;

        private bool promptedSolutionsField;

        private bool showInkAnnotationField;

        private bool backupFileField;

        private bool saveExternalLinkValuesField;

        private ST_UpdateLinks updateLinksField;

        private string codeNameField;

        private bool hidePivotFieldListField;

        private bool showPivotChartFilterField;

        private bool allowRefreshQueryField;

        private bool publishItemsField;

        private bool checkCompatibilityField;

        private bool autoCompressPicturesField;

        private bool refreshAllConnectionsField;

        private uint defaultThemeVersionField;

        private bool defaultThemeVersionFieldSpecified;

        public CT_WorkbookPr()
        {
            this.date1904Field = false;
            this.showObjectsField = ST_Objects.all;
            this.showBorderUnselectedTablesField = true;
            this.filterPrivacyField = false;
            this.promptedSolutionsField = false;
            this.showInkAnnotationField = true;
            this.backupFileField = false;
            this.saveExternalLinkValuesField = true;
            this.updateLinksField = ST_UpdateLinks.userSet;
            this.hidePivotFieldListField = false;
            this.showPivotChartFilterField = false;
            this.allowRefreshQueryField = false;
            this.publishItemsField = false;
            this.checkCompatibilityField = false;
            this.autoCompressPicturesField = true;
            this.refreshAllConnectionsField = false;
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool date1904
        {
            get
            {
                return this.date1904Field;
            }
            set
            {
                this.date1904Field = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_Objects.all)]
        public ST_Objects showObjects
        {
            get
            {
                return this.showObjectsField;
            }
            set
            {
                this.showObjectsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showBorderUnselectedTables
        {
            get
            {
                return this.showBorderUnselectedTablesField;
            }
            set
            {
                this.showBorderUnselectedTablesField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool filterPrivacy
        {
            get
            {
                return this.filterPrivacyField;
            }
            set
            {
                this.filterPrivacyField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool promptedSolutions
        {
            get
            {
                return this.promptedSolutionsField;
            }
            set
            {
                this.promptedSolutionsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool showInkAnnotation
        {
            get
            {
                return this.showInkAnnotationField;
            }
            set
            {
                this.showInkAnnotationField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool backupFile
        {
            get
            {
                return this.backupFileField;
            }
            set
            {
                this.backupFileField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool saveExternalLinkValues
        {
            get
            {
                return this.saveExternalLinkValuesField;
            }
            set
            {
                this.saveExternalLinkValuesField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_UpdateLinks.userSet)]
        public ST_UpdateLinks updateLinks
        {
            get
            {
                return this.updateLinksField;
            }
            set
            {
                this.updateLinksField = value;
            }
        }

        public string codeName
        {
            get
            {
                return this.codeNameField;
            }
            set
            {
                this.codeNameField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool hidePivotFieldList
        {
            get
            {
                return this.hidePivotFieldListField;
            }
            set
            {
                this.hidePivotFieldListField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool showPivotChartFilter
        {
            get
            {
                return this.showPivotChartFilterField;
            }
            set
            {
                this.showPivotChartFilterField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool allowRefreshQuery
        {
            get
            {
                return this.allowRefreshQueryField;
            }
            set
            {
                this.allowRefreshQueryField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool publishItems
        {
            get
            {
                return this.publishItemsField;
            }
            set
            {
                this.publishItemsField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool checkCompatibility
        {
            get
            {
                return this.checkCompatibilityField;
            }
            set
            {
                this.checkCompatibilityField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool autoCompressPictures
        {
            get
            {
                return this.autoCompressPicturesField;
            }
            set
            {
                this.autoCompressPicturesField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool refreshAllConnections
        {
            get
            {
                return this.refreshAllConnectionsField;
            }
            set
            {
                this.refreshAllConnectionsField = value;
            }
        }

        public uint defaultThemeVersion
        {
            get
            {
                return this.defaultThemeVersionField;
            }
            set
            {
                this.defaultThemeVersionField = value;
            }
        }

        public bool defaultThemeVersionSpecified
        {
            get
            {
                return this.defaultThemeVersionFieldSpecified;
            }
            set
            {
                this.defaultThemeVersionFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_UpdateLinks
    {

        /// <remarks/>
        userSet,

        /// <remarks/>
        never,

        /// <remarks/>
        always,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FileSharing
    {

        private bool readOnlyRecommendedField;

        private string userNameField;

        private byte[] reservationPasswordField;

        public CT_FileSharing()
        {
            this.readOnlyRecommendedField = false;
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool readOnlyRecommended
        {
            get
            {
                return this.readOnlyRecommendedField;
            }
            set
            {
                this.readOnlyRecommendedField = value;
            }
        }

        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        public byte[] reservationPassword
        {
            get {                
                return this.reservationPasswordField;
            }
            set
            {
                this.reservationPasswordField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_BookViews
    {

        private List<CT_BookView> workbookViewField;

        public List<CT_BookView> workbookView
        {
            get
            {
                if ((this.workbookViewField == null))
                {
                    this.workbookViewField = new List<CT_BookView>();
                }
                return this.workbookViewField;
            }
            set
            {
                this.workbookViewField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CustomWorkbookViews
    {

        private List<CT_CustomWorkbookView> customWorkbookViewField;

        public List<CT_CustomWorkbookView> customWorkbookView
        {
            get
            {
                if ((this.customWorkbookViewField == null))
                {
                    this.customWorkbookViewField = new List<CT_CustomWorkbookView>();
                }
                return this.customWorkbookViewField;
            }
            set
            {
                this.customWorkbookViewField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Sheets
    {

        private List<CT_Sheet> sheetField;

        public List<CT_Sheet> sheet
        {
            get
            {
                if ((this.sheetField == null))
                {
                    this.sheetField = new List<CT_Sheet>();
                }
                return this.sheetField;
            }
            set
            {
                this.sheetField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_SmartTagTypes
    {

        private List<CT_SmartTagType> smartTagTypeField;

        public List<CT_SmartTagType> smartTagType
        {
            get
            {
                if ((this.smartTagTypeField == null))
                {
                    this.smartTagTypeField = new List<CT_SmartTagType>();
                }
                return this.smartTagTypeField;
            }
            set
            {
                this.smartTagTypeField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_DefinedNames
    {

        private List<CT_DefinedName> definedNameField;

        public List<CT_DefinedName> definedName
        {
            get
            {
                if ((this.definedNameField == null))
                {
                    this.definedNameField = new List<CT_DefinedName>();
                }
                return this.definedNameField;
            }
            set
            {
                this.definedNameField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_ExternalReferences
    {

        private List<CT_ExternalReference> externalReferenceField;

        public List<CT_ExternalReference> externalReference
        {
            get
            {
                if ((this.externalReferenceField == null))
                {
                    this.externalReferenceField = new List<CT_ExternalReference>();
                }
                return this.externalReferenceField;
            }
            set
            {
                this.externalReferenceField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_SheetBackgroundPicture
    {

        private string idField;

        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_PivotCaches
    {

        private List<CT_PivotCache> pivotCacheField;

        public List<CT_PivotCache> pivotCache
        {
            get
            {
                if ((this.pivotCacheField == null))
                {
                    this.pivotCacheField = new List<CT_PivotCache>();
                }
                return this.pivotCacheField;
            }
            set
            {
                this.pivotCacheField = value;
            }
        }
    }
}
