// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.20459
//    <NameSpace>XlsxLib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLasyLoading>True</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XlsxLib
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;     

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Sst
    {

        private List<CT_Rst> siField;

        private CT_ExtensionList extLstField;

        private uint countField;

        private bool countFieldSpecified;

        private uint uniqueCountField;

        private bool uniqueCountFieldSpecified;

        public List<CT_Rst> si
        {
            get
            {
                if ((this.siField == null))
                {
                    this.siField = new List<CT_Rst>();
                }
                return this.siField;
            }
            set
            {
                this.siField = value;
            }
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }

        public uint uniqueCount
        {
            get
            {
                return this.uniqueCountField;
            }
            set
            {
                this.uniqueCountField = value;
            }
        }

        public bool uniqueCountSpecified
        {
            get
            {
                return this.uniqueCountFieldSpecified;
            }
            set
            {
                this.uniqueCountFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Rst
    {

        private string tField;

        private List<CT_RElt> rField;

        private List<CT_PhoneticRun> rPhField;

        private CT_PhoneticPr phoneticPrField;

        public string t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        public List<CT_RElt> r
        {
            get
            {
                if ((this.rField == null))
                {
                    this.rField = new List<CT_RElt>();
                }
                return this.rField;
            }
            set
            {
                this.rField = value;
            }
        }

        public List<CT_PhoneticRun> rPh
        {
            get
            {
                if ((this.rPhField == null))
                {
                    this.rPhField = new List<CT_PhoneticRun>();
                }
                return this.rPhField;
            }
            set
            {
                this.rPhField = value;
            }
        }

        public CT_PhoneticPr phoneticPr
        {
            get
            {
                if ((this.phoneticPrField == null))
                {
                    this.phoneticPrField = new CT_PhoneticPr();
                }
                return this.phoneticPrField;
            }
            set
            {
                this.phoneticPrField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_RElt
    {

        private CT_RPrElt rPrField;

        private string tField;

        public CT_RPrElt rPr
        {
            get
            {
                if ((this.rPrField == null))
                {
                    this.rPrField = new CT_RPrElt();
                }
                return this.rPrField;
            }
            set
            {
                this.rPrField = value;
            }
        }

        public string t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_RPrElt
    {

        private List<object> itemsField;

        private List<ItemsChoiceType1> itemsElementNameField;

        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                if ((this.itemsField == null))
                {
                    this.itemsField = new List<object>();
                }
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public List<ItemsChoiceType1> ItemsElementName
        {
            get
            {
                if ((this.itemsElementNameField == null))
                {
                    this.itemsElementNameField = new List<ItemsChoiceType1>();
                }
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        b,

        /// <remarks/>
        charset,

        /// <remarks/>
        color,

        /// <remarks/>
        condense,

        /// <remarks/>
        extend,

        /// <remarks/>
        family,

        /// <remarks/>
        i,

        /// <remarks/>
        outline,

        /// <remarks/>
        rFont,

        /// <remarks/>
        scheme,

        /// <remarks/>
        shadow,

        /// <remarks/>
        strike,

        /// <remarks/>
        sz,

        /// <remarks/>
        u,

        /// <remarks/>
        vertAlign,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_PhoneticRun
    {

        private string tField;

        private uint sbField;

        private uint ebField;

        public string t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }

        public uint sb
        {
            get
            {
                return this.sbField;
            }
            set
            {
                this.sbField = value;
            }
        }

        public uint eb
        {
            get
            {
                return this.ebField;
            }
            set
            {
                this.ebField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_PhoneticPr
    {

        private uint fontIdField;

        private ST_PhoneticType typeField;

        private ST_PhoneticAlignment alignmentField;

        public CT_PhoneticPr()
        {
            this.typeField = ST_PhoneticType.fullwidthKatakana;
            this.alignmentField = ST_PhoneticAlignment.left;
        }

        public uint fontId
        {
            get
            {
                return this.fontIdField;
            }
            set
            {
                this.fontIdField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_PhoneticType.fullwidthKatakana)]
        public ST_PhoneticType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_PhoneticAlignment.left)]
        public ST_PhoneticAlignment alignment
        {
            get
            {
                if ((this.alignmentField == null))
                {
                    this.alignmentField = new ST_PhoneticAlignment();
                }
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_PhoneticType
    {

        /// <remarks/>
        halfwidthKatakana,

        /// <remarks/>
        fullwidthKatakana,

        /// <remarks/>
        Hiragana,

        /// <remarks/>
        noConversion,
    }

    [System.SerializableAttribute()]
    public enum ST_PhoneticAlignment
    {

        /// <remarks/>
        noControl,

        /// <remarks/>
        left,

        /// <remarks/>
        center,

        /// <remarks/>
        distributed,
    }
}
