// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.20459
//    <NameSpace>XlsxLib</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLasyLoading>True</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XlsxLib
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Stylesheet
    {

        private CT_NumFmts numFmtsField;

        private CT_Fonts fontsField;

        private CT_Fills fillsField;

        private CT_Borders bordersField;

        private CT_CellStyleXfs cellStyleXfsField;

        private CT_CellXfs cellXfsField;

        private CT_CellStyles cellStylesField;

        private CT_Dxfs dxfsField;

        private CT_TableStyles tableStylesField;

        private CT_Colors colorsField;

        private CT_ExtensionList extLstField;

        public CT_NumFmts numFmts
        {
            get
            {
                if ((this.numFmtsField == null))
                {
                    this.numFmtsField = new CT_NumFmts();
                }
                return this.numFmtsField;
            }
            set
            {
                this.numFmtsField = value;
            }
        }

        public CT_Fonts fonts
        {
            get
            {
                if ((this.fontsField == null))
                {
                    this.fontsField = new CT_Fonts();
                }
                return this.fontsField;
            }
            set
            {
                this.fontsField = value;
            }
        }

        public CT_Fills fills
        {
            get
            {
                if ((this.fillsField == null))
                {
                    this.fillsField = new CT_Fills();
                }
                return this.fillsField;
            }
            set
            {
                this.fillsField = value;
            }
        }

        public CT_Borders borders
        {
            get
            {
                if ((this.bordersField == null))
                {
                    this.bordersField = new CT_Borders();
                }
                return this.bordersField;
            }
            set
            {
                this.bordersField = value;
            }
        }

        public CT_CellStyleXfs cellStyleXfs
        {
            get
            {
                if ((this.cellStyleXfsField == null))
                {
                    this.cellStyleXfsField = new CT_CellStyleXfs();
                }
                return this.cellStyleXfsField;
            }
            set
            {
                this.cellStyleXfsField = value;
            }
        }

        public CT_CellXfs cellXfs
        {
            get
            {
                if ((this.cellXfsField == null))
                {
                    this.cellXfsField = new CT_CellXfs();
                }
                return this.cellXfsField;
            }
            set
            {
                this.cellXfsField = value;
            }
        }

        public CT_CellStyles cellStyles
        {
            get
            {
                if ((this.cellStylesField == null))
                {
                    this.cellStylesField = new CT_CellStyles();
                }
                return this.cellStylesField;
            }
            set
            {
                this.cellStylesField = value;
            }
        }

        public CT_Dxfs dxfs
        {
            get
            {
                if ((this.dxfsField == null))
                {
                    this.dxfsField = new CT_Dxfs();
                }
                return this.dxfsField;
            }
            set
            {
                this.dxfsField = value;
            }
        }

        public CT_TableStyles tableStyles
        {
            get
            {
                if ((this.tableStylesField == null))
                {
                    this.tableStylesField = new CT_TableStyles();
                }
                return this.tableStylesField;
            }
            set
            {
                this.tableStylesField = value;
            }
        }

        public CT_Colors colors
        {
            get
            {
                if ((this.colorsField == null))
                {
                    this.colorsField = new CT_Colors();
                }
                return this.colorsField;
            }
            set
            {
                this.colorsField = value;
            }
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_NumFmts
    {

        private List<CT_NumFmt> numFmtField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_NumFmt> numFmt
        {
            get
            {
                if ((this.numFmtField == null))
                {
                    this.numFmtField = new List<CT_NumFmt>();
                }
                return this.numFmtField;
            }
            set
            {
                this.numFmtField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_NumFmt
    {

        private uint numFmtIdField;

        private string formatCodeField;

        public uint numFmtId
        {
            get
            {
                return this.numFmtIdField;
            }
            set
            {
                this.numFmtIdField = value;
            }
        }

        public string formatCode
        {
            get
            {
                return this.formatCodeField;
            }
            set
            {
                this.formatCodeField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_RgbColor
    {

        private byte[] rgbField;

        public byte[] rgb
        {
            get {               
                return this.rgbField;
            }
            set
            {
                this.rgbField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Colors
    {

        private List<CT_RgbColor> indexedColorsField;

        private List<CT_Color> mruColorsField;

        [System.Xml.Serialization.XmlArrayItemAttribute("rgbColor", IsNullable = false)]
        public List<CT_RgbColor> indexedColors
        {
            get
            {
                if ((this.indexedColorsField == null))
                {
                    this.indexedColorsField = new List<CT_RgbColor>();
                }
                return this.indexedColorsField;
            }
            set
            {
                this.indexedColorsField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute("color", IsNullable = false)]
        public List<CT_Color> mruColors
        {
            get
            {
                if ((this.mruColorsField == null))
                {
                    this.mruColorsField = new List<CT_Color>();
                }
                return this.mruColorsField;
            }
            set
            {
                this.mruColorsField = value;
            }
        }
    }   

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_TableStyleElement
    {

        private ST_TableStyleType typeField;

        private uint sizeField;

        private uint dxfIdField;

        private bool dxfIdFieldSpecified;

        public CT_TableStyleElement()
        {
            this.sizeField = ((uint)(1));
        }

        public ST_TableStyleType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "1")]
        public uint size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        public uint dxfId
        {
            get
            {
                return this.dxfIdField;
            }
            set
            {
                this.dxfIdField = value;
            }
        }

        public bool dxfIdSpecified
        {
            get
            {
                return this.dxfIdFieldSpecified;
            }
            set
            {
                this.dxfIdFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_TableStyleType
    {

        /// <remarks/>
        wholeTable,

        /// <remarks/>
        headerRow,

        /// <remarks/>
        totalRow,

        /// <remarks/>
        firstColumn,

        /// <remarks/>
        lastColumn,

        /// <remarks/>
        firstRowStripe,

        /// <remarks/>
        secondRowStripe,

        /// <remarks/>
        firstColumnStripe,

        /// <remarks/>
        secondColumnStripe,

        /// <remarks/>
        firstHeaderCell,

        /// <remarks/>
        lastHeaderCell,

        /// <remarks/>
        firstTotalCell,

        /// <remarks/>
        lastTotalCell,

        /// <remarks/>
        firstSubtotalColumn,

        /// <remarks/>
        secondSubtotalColumn,

        /// <remarks/>
        thirdSubtotalColumn,

        /// <remarks/>
        firstSubtotalRow,

        /// <remarks/>
        secondSubtotalRow,

        /// <remarks/>
        thirdSubtotalRow,

        /// <remarks/>
        blankRow,

        /// <remarks/>
        firstColumnSubheading,

        /// <remarks/>
        secondColumnSubheading,

        /// <remarks/>
        thirdColumnSubheading,

        /// <remarks/>
        firstRowSubheading,

        /// <remarks/>
        secondRowSubheading,

        /// <remarks/>
        thirdRowSubheading,

        /// <remarks/>
        pageFieldLabels,

        /// <remarks/>
        pageFieldValues,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_TableStyle
    {

        private List<CT_TableStyleElement> tableStyleElementField;

        private string nameField;

        private bool pivotField;

        private bool tableField;

        private uint countField;

        private bool countFieldSpecified;

        public CT_TableStyle()
        {
            this.pivotField = true;
            this.tableField = true;
        }

        public List<CT_TableStyleElement> tableStyleElement
        {
            get
            {
                if ((this.tableStyleElementField == null))
                {
                    this.tableStyleElementField = new List<CT_TableStyleElement>();
                }
                return this.tableStyleElementField;
            }
            set
            {
                this.tableStyleElementField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool pivot
        {
            get
            {
                return this.pivotField;
            }
            set
            {
                this.pivotField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool table
        {
            get
            {
                return this.tableField;
            }
            set
            {
                this.tableField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_TableStyles
    {

        private List<CT_TableStyle> tableStyleField;

        private uint countField;

        private bool countFieldSpecified;

        private string defaultTableStyleField;

        private string defaultPivotStyleField;

        public List<CT_TableStyle> tableStyle
        {
            get
            {
                if ((this.tableStyleField == null))
                {
                    this.tableStyleField = new List<CT_TableStyle>();
                }
                return this.tableStyleField;
            }
            set
            {
                this.tableStyleField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }

        public string defaultTableStyle
        {
            get
            {
                return this.defaultTableStyleField;
            }
            set
            {
                this.defaultTableStyleField = value;
            }
        }

        public string defaultPivotStyle
        {
            get
            {
                return this.defaultPivotStyleField;
            }
            set
            {
                this.defaultPivotStyleField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Dxf
    {

        private CT_Font fontField;

        private CT_NumFmt numFmtField;

        private CT_Fill fillField;

        private CT_CellAlignment alignmentField;

        private CT_Border borderField;

        private CT_CellProtection protectionField;

        private CT_ExtensionList extLstField;

        public CT_Font font
        {
            get
            {
                if ((this.fontField == null))
                {
                    this.fontField = new CT_Font();
                }
                return this.fontField;
            }
            set
            {
                this.fontField = value;
            }
        }

        public CT_NumFmt numFmt
        {
            get
            {
                if ((this.numFmtField == null))
                {
                    this.numFmtField = new CT_NumFmt();
                }
                return this.numFmtField;
            }
            set
            {
                this.numFmtField = value;
            }
        }

        public CT_Fill fill
        {
            get
            {
                if ((this.fillField == null))
                {
                    this.fillField = new CT_Fill();
                }
                return this.fillField;
            }
            set
            {
                this.fillField = value;
            }
        }

        public CT_CellAlignment alignment
        {
            get
            {
                if ((this.alignmentField == null))
                {
                    this.alignmentField = new CT_CellAlignment();
                }
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }

        public CT_Border border
        {
            get
            {
                if ((this.borderField == null))
                {
                    this.borderField = new CT_Border();
                }
                return this.borderField;
            }
            set
            {
                this.borderField = value;
            }
        }

        public CT_CellProtection protection
        {
            get
            {
                if ((this.protectionField == null))
                {
                    this.protectionField = new CT_CellProtection();
                }
                return this.protectionField;
            }
            set
            {
                this.protectionField = value;
            }
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Font
    {

        private List<object> itemsField;

        private List<ItemsChoiceType> itemsElementNameField;

        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public List<object> Items
        {
            get
            {
                if ((this.itemsField == null))
                {
                    this.itemsField = new List<object>();
                }
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        public List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                if ((this.itemsElementNameField == null))
                {
                    this.itemsElementNameField = new List<ItemsChoiceType>();
                }
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_BooleanProperty
    {

        private bool valField;

        public CT_BooleanProperty()
        {
            this.valField = true;
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_IntProperty
    {

        private int valField;

        public int val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FontName
    {

        private string valField;

        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FontScheme
    {

        private ST_FontScheme valField;

        public ST_FontScheme val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_FontScheme
    {

        /// <remarks/>
        none,

        /// <remarks/>
        major,

        /// <remarks/>
        minor,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_FontSize
    {

        private double valField;

        public double val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_UnderlineProperty
    {

        private ST_UnderlineValues valField;

        public CT_UnderlineProperty()
        {
            this.valField = ST_UnderlineValues.single;
        }

        [System.ComponentModel.DefaultValueAttribute(ST_UnderlineValues.single)]
        public ST_UnderlineValues val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_UnderlineValues
    {

        /// <remarks/>
        single,

        /// <remarks/>
        @double,

        /// <remarks/>
        singleAccounting,

        /// <remarks/>
        doubleAccounting,

        /// <remarks/>
        none,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_VerticalAlignFontProperty
    {

        private ST_VerticalAlignRun valField;

        public ST_VerticalAlignRun val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_VerticalAlignRun
    {

        /// <remarks/>
        baseline,

        /// <remarks/>
        superscript,

        /// <remarks/>
        subscript,
    }

    [System.SerializableAttribute()]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        b,

        /// <remarks/>
        charset,

        /// <remarks/>
        color,

        /// <remarks/>
        condense,

        /// <remarks/>
        extend,

        /// <remarks/>
        family,

        /// <remarks/>
        i,

        /// <remarks/>
        name,

        /// <remarks/>
        outline,

        /// <remarks/>
        scheme,

        /// <remarks/>
        shadow,

        /// <remarks/>
        strike,

        /// <remarks/>
        sz,

        /// <remarks/>
        u,

        /// <remarks/>
        vertAlign,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Fill
    {

        private object itemField;

        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_GradientFill
    {

        private List<CT_GradientStop> stopField;

        private ST_GradientType typeField;

        private double degreeField;

        private double leftField;

        private double rightField;

        private double topField;

        private double bottomField;

        public CT_GradientFill()
        {
            this.typeField = ST_GradientType.linear;
            this.degreeField = 0D;
            this.leftField = 0D;
            this.rightField = 0D;
            this.topField = 0D;
            this.bottomField = 0D;
        }

        public List<CT_GradientStop> stop
        {
            get
            {
                if ((this.stopField == null))
                {
                    this.stopField = new List<CT_GradientStop>();
                }
                return this.stopField;
            }
            set
            {
                this.stopField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_GradientType.linear)]
        public ST_GradientType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double degree
        {
            get
            {
                return this.degreeField;
            }
            set
            {
                this.degreeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double top
        {
            get
            {
                return this.topField;
            }
            set
            {
                this.topField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double bottom
        {
            get
            {
                return this.bottomField;
            }
            set
            {
                this.bottomField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_GradientStop
    {

        private CT_Color colorField;

        private double positionField;

        public CT_Color color
        {
            get
            {
                if ((this.colorField == null))
                {
                    this.colorField = new CT_Color();
                }
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        public double position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_GradientType
    {

        /// <remarks/>
        linear,

        /// <remarks/>
        path,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_PatternFill
    {

        private CT_Color fgColorField;

        private CT_Color bgColorField;

        private ST_PatternType patternTypeField;

        private bool patternTypeFieldSpecified;

        public CT_Color fgColor
        {
            get
            {
                if ((this.fgColorField == null))
                {
                    this.fgColorField = new CT_Color();
                }
                return this.fgColorField;
            }
            set
            {
                this.fgColorField = value;
            }
        }

        public CT_Color bgColor
        {
            get
            {
                if ((this.bgColorField == null))
                {
                    this.bgColorField = new CT_Color();
                }
                return this.bgColorField;
            }
            set
            {
                this.bgColorField = value;
            }
        }

        public ST_PatternType patternType
        {
            get
            {
                return this.patternTypeField;
            }
            set
            {
                this.patternTypeField = value;
            }
        }

        public bool patternTypeSpecified
        {
            get
            {
                return this.patternTypeFieldSpecified;
            }
            set
            {
                this.patternTypeFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_PatternType
    {

        /// <remarks/>
        none,

        /// <remarks/>
        solid,

        /// <remarks/>
        mediumGray,

        /// <remarks/>
        darkGray,

        /// <remarks/>
        lightGray,

        /// <remarks/>
        darkHorizontal,

        /// <remarks/>
        darkVertical,

        /// <remarks/>
        darkDown,

        /// <remarks/>
        darkUp,

        /// <remarks/>
        darkGrid,

        /// <remarks/>
        darkTrellis,

        /// <remarks/>
        lightHorizontal,

        /// <remarks/>
        lightVertical,

        /// <remarks/>
        lightDown,

        /// <remarks/>
        lightUp,

        /// <remarks/>
        lightGrid,

        /// <remarks/>
        lightTrellis,

        /// <remarks/>
        gray125,

        /// <remarks/>
        gray0625,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellAlignment
    {

        private ST_HorizontalAlignment horizontalField;

        private bool horizontalFieldSpecified;

        private ST_VerticalAlignment verticalField;

        private bool verticalFieldSpecified;

        private uint textRotationField;

        private bool textRotationFieldSpecified;

        private bool wrapTextField;

        private bool wrapTextFieldSpecified;

        private uint indentField;

        private bool indentFieldSpecified;

        private int relativeIndentField;

        private bool relativeIndentFieldSpecified;

        private bool justifyLastLineField;

        private bool justifyLastLineFieldSpecified;

        private bool shrinkToFitField;

        private bool shrinkToFitFieldSpecified;

        private uint readingOrderField;

        private bool readingOrderFieldSpecified;

        public ST_HorizontalAlignment horizontal
        {
            get
            {
                return this.horizontalField;
            }
            set
            {
                this.horizontalField = value;
            }
        }

        public bool horizontalSpecified
        {
            get
            {
                return this.horizontalFieldSpecified;
            }
            set
            {
                this.horizontalFieldSpecified = value;
            }
        }

        public ST_VerticalAlignment vertical
        {
            get
            {
                return this.verticalField;
            }
            set
            {
                this.verticalField = value;
            }
        }

        public bool verticalSpecified
        {
            get
            {
                return this.verticalFieldSpecified;
            }
            set
            {
                this.verticalFieldSpecified = value;
            }
        }

        public uint textRotation
        {
            get
            {
                return this.textRotationField;
            }
            set
            {
                this.textRotationField = value;
            }
        }

        public bool textRotationSpecified
        {
            get
            {
                return this.textRotationFieldSpecified;
            }
            set
            {
                this.textRotationFieldSpecified = value;
            }
        }

        public bool wrapText
        {
            get
            {
                return this.wrapTextField;
            }
            set
            {
                this.wrapTextField = value;
            }
        }

        public bool wrapTextSpecified
        {
            get
            {
                return this.wrapTextFieldSpecified;
            }
            set
            {
                this.wrapTextFieldSpecified = value;
            }
        }

        public uint indent
        {
            get
            {
                return this.indentField;
            }
            set
            {
                this.indentField = value;
            }
        }

        public bool indentSpecified
        {
            get
            {
                return this.indentFieldSpecified;
            }
            set
            {
                this.indentFieldSpecified = value;
            }
        }

        public int relativeIndent
        {
            get
            {
                return this.relativeIndentField;
            }
            set
            {
                this.relativeIndentField = value;
            }
        }

        public bool relativeIndentSpecified
        {
            get
            {
                return this.relativeIndentFieldSpecified;
            }
            set
            {
                this.relativeIndentFieldSpecified = value;
            }
        }

        public bool justifyLastLine
        {
            get
            {
                return this.justifyLastLineField;
            }
            set
            {
                this.justifyLastLineField = value;
            }
        }

        public bool justifyLastLineSpecified
        {
            get
            {
                return this.justifyLastLineFieldSpecified;
            }
            set
            {
                this.justifyLastLineFieldSpecified = value;
            }
        }

        public bool shrinkToFit
        {
            get
            {
                return this.shrinkToFitField;
            }
            set
            {
                this.shrinkToFitField = value;
            }
        }

        public bool shrinkToFitSpecified
        {
            get
            {
                return this.shrinkToFitFieldSpecified;
            }
            set
            {
                this.shrinkToFitFieldSpecified = value;
            }
        }

        public uint readingOrder
        {
            get
            {
                return this.readingOrderField;
            }
            set
            {
                this.readingOrderField = value;
            }
        }

        public bool readingOrderSpecified
        {
            get
            {
                return this.readingOrderFieldSpecified;
            }
            set
            {
                this.readingOrderFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_HorizontalAlignment
    {

        /// <remarks/>
        general,

        /// <remarks/>
        left,

        /// <remarks/>
        center,

        /// <remarks/>
        right,

        /// <remarks/>
        fill,

        /// <remarks/>
        justify,

        /// <remarks/>
        centerContinuous,

        /// <remarks/>
        distributed,
    }

    [System.SerializableAttribute()]
    public enum ST_VerticalAlignment
    {

        /// <remarks/>
        top,

        /// <remarks/>
        center,

        /// <remarks/>
        bottom,

        /// <remarks/>
        justify,

        /// <remarks/>
        distributed,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Border
    {

        private CT_BorderPr leftField;

        private CT_BorderPr rightField;

        private CT_BorderPr topField;

        private CT_BorderPr bottomField;

        private CT_BorderPr diagonalField;

        private CT_BorderPr verticalField;

        private CT_BorderPr horizontalField;

        private bool diagonalUpField;

        private bool diagonalUpFieldSpecified;

        private bool diagonalDownField;

        private bool diagonalDownFieldSpecified;

        private bool outlineField;

        public CT_Border()
        {
            this.outlineField = true;
        }

        public CT_BorderPr left
        {
            get
            {
                if ((this.leftField == null))
                {
                    this.leftField = new CT_BorderPr();
                }
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }

        public CT_BorderPr right
        {
            get
            {
                if ((this.rightField == null))
                {
                    this.rightField = new CT_BorderPr();
                }
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }

        public CT_BorderPr top
        {
            get
            {
                if ((this.topField == null))
                {
                    this.topField = new CT_BorderPr();
                }
                return this.topField;
            }
            set
            {
                this.topField = value;
            }
        }

        public CT_BorderPr bottom
        {
            get
            {
                if ((this.bottomField == null))
                {
                    this.bottomField = new CT_BorderPr();
                }
                return this.bottomField;
            }
            set
            {
                this.bottomField = value;
            }
        }

        public CT_BorderPr diagonal
        {
            get
            {
                if ((this.diagonalField == null))
                {
                    this.diagonalField = new CT_BorderPr();
                }
                return this.diagonalField;
            }
            set
            {
                this.diagonalField = value;
            }
        }

        public CT_BorderPr vertical
        {
            get
            {
                if ((this.verticalField == null))
                {
                    this.verticalField = new CT_BorderPr();
                }
                return this.verticalField;
            }
            set
            {
                this.verticalField = value;
            }
        }

        public CT_BorderPr horizontal
        {
            get
            {
                if ((this.horizontalField == null))
                {
                    this.horizontalField = new CT_BorderPr();
                }
                return this.horizontalField;
            }
            set
            {
                this.horizontalField = value;
            }
        }

        public bool diagonalUp
        {
            get
            {
                return this.diagonalUpField;
            }
            set
            {
                this.diagonalUpField = value;
            }
        }

        public bool diagonalUpSpecified
        {
            get
            {
                return this.diagonalUpFieldSpecified;
            }
            set
            {
                this.diagonalUpFieldSpecified = value;
            }
        }

        public bool diagonalDown
        {
            get
            {
                return this.diagonalDownField;
            }
            set
            {
                this.diagonalDownField = value;
            }
        }

        public bool diagonalDownSpecified
        {
            get
            {
                return this.diagonalDownFieldSpecified;
            }
            set
            {
                this.diagonalDownFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool outline
        {
            get
            {
                return this.outlineField;
            }
            set
            {
                this.outlineField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_BorderPr
    {

        private CT_Color colorField;

        private ST_BorderStyle styleField;

        public CT_BorderPr()
        {
            this.styleField = ST_BorderStyle.none;
        }

        public CT_Color color
        {
            get
            {
                if ((this.colorField == null))
                {
                    this.colorField = new CT_Color();
                }
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(ST_BorderStyle.none)]
        public ST_BorderStyle style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public enum ST_BorderStyle
    {

        /// <remarks/>
        none,

        /// <remarks/>
        thin,

        /// <remarks/>
        medium,

        /// <remarks/>
        dashed,

        /// <remarks/>
        dotted,

        /// <remarks/>
        thick,

        /// <remarks/>
        @double,

        /// <remarks/>
        hair,

        /// <remarks/>
        mediumDashed,

        /// <remarks/>
        dashDot,

        /// <remarks/>
        mediumDashDot,

        /// <remarks/>
        dashDotDot,

        /// <remarks/>
        mediumDashDotDot,

        /// <remarks/>
        slantDashDot,
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellProtection
    {

        private bool lockedField;

        private bool lockedFieldSpecified;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        public bool locked
        {
            get
            {
                return this.lockedField;
            }
            set
            {
                this.lockedField = value;
            }
        }

        public bool lockedSpecified
        {
            get
            {
                return this.lockedFieldSpecified;
            }
            set
            {
                this.lockedFieldSpecified = value;
            }
        }

        public bool hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        public bool hiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }
    }
   

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Dxfs
    {

        private List<CT_Dxf> dxfField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Dxf> dxf
        {
            get
            {
                if ((this.dxfField == null))
                {
                    this.dxfField = new List<CT_Dxf>();
                }
                return this.dxfField;
            }
            set
            {
                this.dxfField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellStyle
    {

        private CT_ExtensionList extLstField;

        private string nameField;

        private uint xfIdField;

        private uint builtinIdField;

        private bool builtinIdFieldSpecified;

        private uint iLevelField;

        private bool iLevelFieldSpecified;

        private bool hiddenField;

        private bool hiddenFieldSpecified;

        private bool customBuiltinField;

        private bool customBuiltinFieldSpecified;

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public uint xfId
        {
            get
            {
                return this.xfIdField;
            }
            set
            {
                this.xfIdField = value;
            }
        }

        public uint builtinId
        {
            get
            {
                return this.builtinIdField;
            }
            set
            {
                this.builtinIdField = value;
            }
        }

        public bool builtinIdSpecified
        {
            get
            {
                return this.builtinIdFieldSpecified;
            }
            set
            {
                this.builtinIdFieldSpecified = value;
            }
        }

        public uint iLevel
        {
            get
            {
                return this.iLevelField;
            }
            set
            {
                this.iLevelField = value;
            }
        }

        public bool iLevelSpecified
        {
            get
            {
                return this.iLevelFieldSpecified;
            }
            set
            {
                this.iLevelFieldSpecified = value;
            }
        }

        public bool hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }

        public bool hiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }

        public bool customBuiltin
        {
            get
            {
                return this.customBuiltinField;
            }
            set
            {
                this.customBuiltinField = value;
            }
        }

        public bool customBuiltinSpecified
        {
            get
            {
                return this.customBuiltinFieldSpecified;
            }
            set
            {
                this.customBuiltinFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellStyles
    {

        private List<CT_CellStyle> cellStyleField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_CellStyle> cellStyle
        {
            get
            {
                if ((this.cellStyleField == null))
                {
                    this.cellStyleField = new List<CT_CellStyle>();
                }
                return this.cellStyleField;
            }
            set
            {
                this.cellStyleField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellXfs
    {

        private List<CT_Xf> xfField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Xf> xf
        {
            get
            {
                if ((this.xfField == null))
                {
                    this.xfField = new List<CT_Xf>();
                }
                return this.xfField;
            }
            set
            {
                this.xfField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Xf
    {

        private CT_CellAlignment alignmentField;

        private CT_CellProtection protectionField;

        private CT_ExtensionList extLstField;

        private uint numFmtIdField;

        private bool numFmtIdFieldSpecified;

        private uint fontIdField;

        private bool fontIdFieldSpecified;

        private uint fillIdField;

        private bool fillIdFieldSpecified;

        private uint borderIdField;

        private bool borderIdFieldSpecified;

        private uint xfIdField;

        private bool xfIdFieldSpecified;

        private bool quotePrefixField;

        private bool pivotButtonField;

        private bool applyNumberFormatField;

        private bool applyNumberFormatFieldSpecified;

        private bool applyFontField;

        private bool applyFontFieldSpecified;

        private bool applyFillField;

        private bool applyFillFieldSpecified;

        private bool applyBorderField;

        private bool applyBorderFieldSpecified;

        private bool applyAlignmentField;

        private bool applyAlignmentFieldSpecified;

        private bool applyProtectionField;

        private bool applyProtectionFieldSpecified;

        public CT_Xf()
        {
            this.quotePrefixField = false;
            this.pivotButtonField = false;
        }

        public CT_CellAlignment alignment
        {
            get
            {
                if ((this.alignmentField == null))
                {
                    this.alignmentField = new CT_CellAlignment();
                }
                return this.alignmentField;
            }
            set
            {
                this.alignmentField = value;
            }
        }

        public CT_CellProtection protection
        {
            get
            {
                if ((this.protectionField == null))
                {
                    this.protectionField = new CT_CellProtection();
                }
                return this.protectionField;
            }
            set
            {
                this.protectionField = value;
            }
        }

        public CT_ExtensionList extLst
        {
            get
            {
                if ((this.extLstField == null))
                {
                    this.extLstField = new CT_ExtensionList();
                }
                return this.extLstField;
            }
            set
            {
                this.extLstField = value;
            }
        }

        public uint numFmtId
        {
            get
            {
                return this.numFmtIdField;
            }
            set
            {
                this.numFmtIdField = value;
            }
        }

        public bool numFmtIdSpecified
        {
            get
            {
                return this.numFmtIdFieldSpecified;
            }
            set
            {
                this.numFmtIdFieldSpecified = value;
            }
        }

        public uint fontId
        {
            get
            {
                return this.fontIdField;
            }
            set
            {
                this.fontIdField = value;
            }
        }

        public bool fontIdSpecified
        {
            get
            {
                return this.fontIdFieldSpecified;
            }
            set
            {
                this.fontIdFieldSpecified = value;
            }
        }

        public uint fillId
        {
            get
            {
                return this.fillIdField;
            }
            set
            {
                this.fillIdField = value;
            }
        }

        public bool fillIdSpecified
        {
            get
            {
                return this.fillIdFieldSpecified;
            }
            set
            {
                this.fillIdFieldSpecified = value;
            }
        }

        public uint borderId
        {
            get
            {
                return this.borderIdField;
            }
            set
            {
                this.borderIdField = value;
            }
        }

        public bool borderIdSpecified
        {
            get
            {
                return this.borderIdFieldSpecified;
            }
            set
            {
                this.borderIdFieldSpecified = value;
            }
        }

        public uint xfId
        {
            get
            {
                return this.xfIdField;
            }
            set
            {
                this.xfIdField = value;
            }
        }

        public bool xfIdSpecified
        {
            get
            {
                return this.xfIdFieldSpecified;
            }
            set
            {
                this.xfIdFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool quotePrefix
        {
            get
            {
                return this.quotePrefixField;
            }
            set
            {
                this.quotePrefixField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool pivotButton
        {
            get
            {
                return this.pivotButtonField;
            }
            set
            {
                this.pivotButtonField = value;
            }
        }

        public bool applyNumberFormat
        {
            get
            {
                return this.applyNumberFormatField;
            }
            set
            {
                this.applyNumberFormatField = value;
            }
        }

        public bool applyNumberFormatSpecified
        {
            get
            {
                return this.applyNumberFormatFieldSpecified;
            }
            set
            {
                this.applyNumberFormatFieldSpecified = value;
            }
        }

        public bool applyFont
        {
            get
            {
                return this.applyFontField;
            }
            set
            {
                this.applyFontField = value;
            }
        }

        public bool applyFontSpecified
        {
            get
            {
                return this.applyFontFieldSpecified;
            }
            set
            {
                this.applyFontFieldSpecified = value;
            }
        }

        public bool applyFill
        {
            get
            {
                return this.applyFillField;
            }
            set
            {
                this.applyFillField = value;
            }
        }

        public bool applyFillSpecified
        {
            get
            {
                return this.applyFillFieldSpecified;
            }
            set
            {
                this.applyFillFieldSpecified = value;
            }
        }

        public bool applyBorder
        {
            get
            {
                return this.applyBorderField;
            }
            set
            {
                this.applyBorderField = value;
            }
        }

        public bool applyBorderSpecified
        {
            get
            {
                return this.applyBorderFieldSpecified;
            }
            set
            {
                this.applyBorderFieldSpecified = value;
            }
        }

        public bool applyAlignment
        {
            get
            {
                return this.applyAlignmentField;
            }
            set
            {
                this.applyAlignmentField = value;
            }
        }

        public bool applyAlignmentSpecified
        {
            get
            {
                return this.applyAlignmentFieldSpecified;
            }
            set
            {
                this.applyAlignmentFieldSpecified = value;
            }
        }

        public bool applyProtection
        {
            get
            {
                return this.applyProtectionField;
            }
            set
            {
                this.applyProtectionField = value;
            }
        }

        public bool applyProtectionSpecified
        {
            get
            {
                return this.applyProtectionFieldSpecified;
            }
            set
            {
                this.applyProtectionFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_CellStyleXfs
    {

        private List<CT_Xf> xfField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Xf> xf
        {
            get
            {
                if ((this.xfField == null))
                {
                    this.xfField = new List<CT_Xf>();
                }
                return this.xfField;
            }
            set
            {
                this.xfField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Borders
    {

        private List<CT_Border> borderField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Border> border
        {
            get
            {
                if ((this.borderField == null))
                {
                    this.borderField = new List<CT_Border>();
                }
                return this.borderField;
            }
            set
            {
                this.borderField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Fills
    {

        private List<CT_Fill> fillField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Fill> fill
        {
            get
            {
                if ((this.fillField == null))
                {
                    this.fillField = new List<CT_Fill>();
                }
                return this.fillField;
            }
            set
            {
                this.fillField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_Fonts
    {

        private List<CT_Font> fontField;

        private uint countField;

        private bool countFieldSpecified;

        public List<CT_Font> font
        {
            get
            {
                if ((this.fontField == null))
                {
                    this.fontField = new List<CT_Font>();
                }
                return this.fontField;
            }
            set
            {
                this.fontField = value;
            }
        }

        public uint count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_IndexedColors
    {

        private List<CT_RgbColor> rgbColorField;

        public List<CT_RgbColor> rgbColor
        {
            get
            {
                if ((this.rgbColorField == null))
                {
                    this.rgbColorField = new List<CT_RgbColor>();
                }
                return this.rgbColorField;
            }
            set
            {
                this.rgbColorField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_MRUColors
    {

        private List<CT_Color> colorField;

        public List<CT_Color> color
        {
            get
            {
                if ((this.colorField == null))
                {
                    this.colorField = new List<CT_Color>();
                }
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
    }
}
